site_name: Geostat Documentation

nav:
  - Home: index.md
  - API Reference:
    - Featurizer: featurizer.md
    - GP: gp.md
    - Kernel:
      - Kernel: kernel_kernel.md
      - Constant: kernel_constant.md
      - Delta: kernel_delta.md
      - GammaExponential: kernel_gammaexponential.md
      - IntExponential: kernel_intexponential.md
      - IntSquaredExponential: kernel_intsquaredexponential.md
      - Mix: kernel_mix.md
      - Noise: kernel_noise.md
      - Product: kernel_product.md
      - QuadStack: kernel_quadstack.md
      - Ramp: kernel_ramp.md
      - RampStack: kernel_rampstack.md
      - SmoothConvex: kernel_smoothconvex.md
      - SquaredExponential: kernel_squaredexponential.md
      - Stack: kernel_stack.md
      - TrendPrior: kernel_trendprior.md
      - Wiener: kernel_wiener.md
    - Mix: mix.md
    - Model: model.md
    - NormalizingFeaturizer: normalizingfeaturizer.md
  - Examples: examples.md
  - About: about.md

hide:
  - toc

theme:
  name: "material"

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - style.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js