[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "geostat"
version = "0.11.1"
description = "Model spatial data with Gaussian processes"
readme = "README.md"
license = "Apache-2.0"
authors = [
  "Michael J. Stephens <mjstephens@usgs.gov>",
  "Will Chang <will@hypergradient.ai>"
]
keywords = ["geospatial", "spatial", "interpolation", "gaussian process", "krige", "kriging"]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3"
]

[tool.poetry.urls]
Homepage = "https://github.com/whdc/geostat"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
matplotlib = ">=3.0"
numpy = ">=1.19"
pandas = ">=1.2"
scipy = ">=1.5"
shapely = ">=1.8"
jax = { version = ">=0.4.34", extras = ["cuda12"] }
optax = ">=0"
pyproj = { version = ">=3.0", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = ">=3.0"

[tool.poetry.extras]
extras = ["pyproj"]
